annotations:
  reloader.stakater.com/auto: "true"

service:
  management:
    enabled: true

deployments:
  standalone:
    enabled: false
  webserver:
    enabled: true
    autoscaler:
      enabled: false
  executor:
    enabled: true
  indexer:
    enabled: true
  scheduler:
    enabled: true
  worker:
    enabled: false

externalSecret:
  secretName: kestra-external-configuration
  key: application-kestra.yml

dind:
  enabled: false

kafka:
  enabled: false

elasticsearch:
  enabled: false

minio:
  enabled: false

postgresql:
  enabled: false
    
ingress:
  enabled: true
  className: 'nginx'
  hosts:
    - host: kestra.docker.localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
