{{- range $provider := .Values.nomad.providers }}
---
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: nomad-{{ $provider.region }}
spec:
  configuration: |
    terraform {
      backend "kubernetes" {
        secret_suffix     = "nomad-{{ $provider.region }}"
        namespace         = "crossplane-system"
        in_cluster_config = true
      }
      required_providers {
        nomad = {
          source = "hashicorp/nomad"
          version = "2.4.0"
        }
      }
    }
    provider "nomad" {
      {{- range $key, $val := $provider }}
      {{ $key }} = "{{ $val }}"
      {{- end }}
    }
{{- end }}
