http:
  services:
    argo-cd:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.49.2"
  routers:
    argo-cd:
      rule: "Host(`argo-cd.docker.localhost`)"
      service: argo-cd@file
