http:
  services:
    kestra:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.49.2"
  routers:
    kestra:
      rule: "Host(`kestra.docker.localhost`)"
      service: kestra@file
