services:

  nomad-europe-paris-1:
    image: 'hashicorp/nomad:1.9.3'
    container_name: 'nomad-europe-paris-1'
    env_file: '.env'
    command: 'agent -node=nomad-europe-paris-1 -config=/etc/nomad/config.hcl -config=/etc/nomad/paris.hcl'
    privileged: true
    environment:
      - NOMAD_SKIP_DOCKER_IMAGE_WARN=true
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nomad-europe-paris.rule=Host(`nomad.europe-paris.docker.localhost`)'
      - 'traefik.http.routers.nomad-europe-paris.entrypoints=web'
      - 'traefik.http.services.nomad-europe-paris.loadbalancer.server.port=4646'
    volumes:
      - './configs/nomad/server/default.hcl:/etc/nomad/config.hcl:ro'
      - './configs/nomad/server/paris.hcl:/etc/nomad/paris.hcl:ro'
      - 'nomad_europe_paris_1_data:/opt/nomad'
    networks:
      minikube:
        ipv4_address: '${IP_NOMAD_SERVER_1}'

  nomad-europe-paris-2:
    image: 'hashicorp/nomad:1.9.3'
    container_name: 'nomad-europe-paris-2'
    env_file: '.env'
    command: 'agent -node=nomad-europe-paris-2 -config=/etc/nomad/config.hcl -config=/etc/nomad/paris.hcl'
    privileged: true
    environment:
      - NOMAD_SKIP_DOCKER_IMAGE_WARN=true
    volumes:
      - './configs/nomad/server/default.hcl:/etc/nomad/config.hcl:ro'
      - './configs/nomad/server/paris.hcl:/etc/nomad/paris.hcl:ro'
      - 'nomad_europe_paris_2_data:/opt/nomad'
    networks:
      minikube:
        ipv4_address: '${IP_NOMAD_SERVER_2}'

  nomad-europe-paris-3:
    image: 'hashicorp/nomad:1.9.3'
    env_file: '.env'
    container_name: 'nomad-europe-paris-3'
    command: 'agent -node=nomad-europe-paris-3 -config=/etc/nomad/config.hcl -config=/etc/nomad/paris.hcl'
    privileged: true
    environment:
      - NOMAD_SKIP_DOCKER_IMAGE_WARN=true
    volumes:
      - './configs/nomad/server/default.hcl:/etc/nomad/config.hcl:ro'
      - './configs/nomad/server/paris.hcl:/etc/nomad/paris.hcl:ro'
      - 'nomad_europe_paris_3_data:/opt/nomad'
    networks:
      minikube:
        ipv4_address: '${IP_NOMAD_SERVER_3}'

networks:

  minikube:
    name: minikube
    external: true

volumes:

  nomad_europe_paris_1_data: {}
  nomad_europe_paris_2_data: {}
  nomad_europe_paris_3_data: {}
