services:

  traefik:
    image: 'traefik:v3.2.2'
    container_name: 'traefik'
    env_file: '.env'
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.nomad=true'
      - '--providers.nomad.endpoint.address=http://nomad-europe-paris-1:4646'
      - '--providers.nomad.exposedByDefault=false'
      - '--entryPoints.web.address=:80'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik-dashboard.rule=Host(`traefik.docker.localhost`)'
      - 'traefik.http.routers.traefik-dashboard.entrypoints=web'
      - 'traefik.http.routers.traefik-dashboard.service=api@internal'
    ports:
      - '80:80/tcp'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      minikube:
        ipv4_address: '${IP_TRAEFIK}'

  keycloak:
    depends_on:
      - keycloak-postgres
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    env_file: '.env'
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=changeme
      - KC_HOSTNAME=keycloak.docker.localhost
      - KC_HOSTNAME_PORT=8080
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_LOG_LEVEL=info
      - KC_METRICS_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=changeme
    command:
      - start-dev
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.keycloak.rule=Host(`keycloak.docker.localhost`)'
      - 'traefik.http.routers.keycloak.entrypoints=web'
      - 'traefik.http.services.keycloak.loadbalancer.server.port=8080'
    networks:
      minikube:
        ipv4_address: '${IP_KEYCLOACK}'

  keycloak-postgres:
    image: postgres:14.15-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=changeme
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      minikube: {}

volumes:

  keycloak_postgres_data: {}

networks:

  minikube:
    name: minikube
    external: true
