name: k8s-nomad-operator

include:
  - compose/services/traefik.yaml
  - compose/services/kestra.yaml
  - compose/services/keycloak.yaml
  - compose/services/nomad-europe-paris.yaml

networks:
  minikube:
    name: 'minikube-network'
    external: true
