apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-prometheusRule.yaml
  - kubernetes-serviceMonitorApiserver.yaml
  - kubernetes-serviceMonitorCoreDNS.yaml
  - kubernetes-serviceMonitorKubeControllerManager.yaml
  - kubernetes-serviceMonitorKubelet.yaml
  - kubernetes-serviceMonitorKubeScheduler.yaml
