---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: kestra-scrape-config
  namespace: monitoring-system
spec:
  jobName: "kestra"
  metricsPath: "/prometheus"
  staticConfigs:
    - targets:
        - "kestra-service.kestra-system:8081"

---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: kestra-nomad-scrape-config
  namespace: monitoring-system
spec:
  jobName: "kestra-nomad"
  NomadSDConfigs:
    - server: "http://192.168.49.21:4646"
      namespace: "kestra-system"
  metricRelabelings:
    - sourceLabels: [__meta_nomad_job_name]
      regex: ".*"
      targetLabel: job
    - sourceLabels: [__meta_nomad_task_name]
      targetLabel: task
    - sourceLabels: [__meta_nomad_alloc_id]
      targetLabel: alloc_id
  metricsPath: "/prometheus"
  scheme: "HTTP"
