deployments:
  standalone:
    enabled: false
  webserver:
    enabled: true
    autoscaler:
      enabled: false
  executor:
    enabled: true
  indexer:
    enabled: true
  scheduler:
    enabled: true
  worker:
    enabled: true

configuration:
  datasources:
    postgres:
      url: 'jdbc:postgresql://192.168.49.60:5432/kestra'
      driverClassName: org.postgresql.Driver
  kestra:
    tutorialFlows:
      enabled: false
    queue:
      type: postgres
    repository:
      type: postgres

extraEnv:
  - name: DATASOURCES_POSTGRES_USERNAME
    value: 'kestra'
  - name: DATASOURCES_POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: kestra-postgresql-auth
        key: USER_PASSWORD

dind:
  enabled: false

kafka:
  enabled: false

elasticsearch:
  enabled: false

minio:
  enabled: true

postgresql:
  enabled: false
    
ingress:
  enabled: true
  className: 'nginx'
  hosts:
    - host: kestra.docker.localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
