---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thanos-query-frontend
spec:
  ingressClassName: nginx
  rules:
  - host: thanos-query-frontend.docker.localhost
    http:
      paths:
      - backend:
          service:
            name: thanos-query-frontend
            port:
              number: 9090
        path: /
        pathType: ImplementationSpecific
