---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thanos-query
spec:
  ingressClassName: nginx
  rules:
  - host: thanos-query.docker.localhost
    http:
      paths:
      - backend:
          service:
            name: thanos-query
            port:
              number: 9090
        path: /
        pathType: ImplementationSpecific
