http:
  services:
    grafana:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://minikube"
  routers:
    grafana:
      rule: "Host(`grafana.docker.localhost`)"
      service: grafana@file
