http:
  services:
    thanos-store:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://minikube"
  routers:
    thanos-store:
      rule: "Host(`thanos-store.docker.localhost`)"
      service: thanos-store@file
