http:
  services:
    thanos-query:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://minikube"
  routers:
    thanos-query:
      rule: "Host(`thanos-query.docker.localhost`)"
      service: thanos-query@file
