apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring-system

# https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/

resources:
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/prometheus-clusterRole.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/prometheus-clusterRoleBinding.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/prometheus-networkPolicy.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/prometheus-podDisruptionBudget.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/prometheus-prometheus.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/prometheus-prometheusRule.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/prometheus-roleBindingConfig.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/prometheus-roleBindingSpecificNamespaces.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/prometheus-roleConfig.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/prometheus-roleSpecificNamespaces.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/prometheus-service.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/prometheus-serviceAccount.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/prometheus-serviceMonitor.yaml

patchesStrategicMerge:
  - patchs/prometheus-prometheus.yaml.yaml