apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifests/prometheus-clusterRole.yaml
  - ./manifests/prometheus-clusterRoleBinding.yaml
  - ./manifests/prometheus-networkPolicy.yaml
  - ./manifests/prometheus-podDisruptionBudget.yaml
  - ./manifests/prometheus-prometheusRule.yaml
  - ./files/prometheus-roleBindingConfig.yaml
  - ./manifests/prometheus-roleBindingSpecificNamespaces.yaml
  - ./manifests/prometheus-roleConfig.yaml
  - ./manifests/prometheus-roleSpecificNamespaces.yaml
  - ./files/prometheus-prometheus.yaml
  - ./manifests/prometheus-service.yaml
  - ./manifests/prometheus-serviceAccount.yaml
  - ./manifests/prometheus-serviceMonitor.yaml
  - ./files/ingress.yaml
