apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring-system

# https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/

resources:
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/setup/0alertmanagerCustomResourceDefinition.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/setup/0podmonitorCustomResourceDefinition.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/setup/0probeCustomResourceDefinition.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/setup/0prometheusCustomResourceDefinition.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/setup/0prometheusagentCustomResourceDefinition.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/setup/0prometheusruleCustomResourceDefinition.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/setup/0scrapeconfigCustomResourceDefinition.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/setup/0servicemonitorCustomResourceDefinition.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/setup/0thanosrulerCustomResourceDefinition.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/setup/0alertmanagerConfigCustomResourceDefinition.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/prometheusOperator-service.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/prometheusOperator-serviceAccount.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/prometheusOperator-clusterRole.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/prometheusOperator-clusterRoleBinding.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/prometheusOperator-networkPolicy.yaml

patchesStrategicMerge:
  - patches/patch-prometheusOperator-service.yaml
  - patches/patch-prometheusOperator-serviceAccount.yaml
  - patches/prometheusOperator-networkPolicy.yaml
