apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring-system

resources:
  - ./manifests/setup/0alertmanagerCustomResourceDefinition.yaml
  - ./manifests/setup/0podmonitorCustomResourceDefinition.yaml
  - ./manifests/setup/0probeCustomResourceDefinition.yaml
  - ./manifests/setup/0prometheusCustomResourceDefinition.yaml
  - ./manifests/setup/0prometheusagentCustomResourceDefinition.yaml
  - ./manifests/setup/0prometheusruleCustomResourceDefinition.yaml
  - ./manifests/setup/0scrapeconfigCustomResourceDefinition.yaml
  - ./manifests/setup/0servicemonitorCustomResourceDefinition.yaml
  - ./manifests/setup/0thanosrulerCustomResourceDefinition.yaml
  - ./manifests/setup/0alertmanagerConfigCustomResourceDefinition.yaml
  - ./manifests/prometheusOperator-service.yaml
  - ./manifests/prometheusOperator-serviceAccount.yaml
  - ./manifests/prometheusOperator-clusterRole.yaml
  - ./manifests/prometheusOperator-clusterRoleBinding.yaml
  - ./manifests/prometheusOperator-networkPolicy.yaml
  - ./manifests/prometheusOperator-deployment.yaml

patches:
  - path: ./patches/prometheusOperator-clusterRoleBinding.yaml
    target:
      version: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      name: prometheus-operator
