services:

  keycloak:
    depends_on:
      - 'keycloak-postgres'
    image: 'quay.io/keycloak/keycloak:26.0.7'
    container_name: 'keycloak'
    environment:
      KC_DB: 'postgres'
      KC_DB_URL: 'jdbc:postgresql://keycloak-postgres:5432/keycloak'
      KC_DB_USERNAME: 'keycloak'
      KC_DB_PASSWORD: 'changeme'
      KC_HOSTNAME: 'keycloak.docker.localhost'
      KC_HOSTNAME_PORT: '8080'
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_LOG_LEVEL: 'info'
      KC_METRICS_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'changeme'
    command:
      - 'start-dev'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.keycloak.rule=Host(`keycloak.docker.localhost`)'
      - 'traefik.http.routers.keycloak.entrypoints=web'
      - 'traefik.http.services.keycloak.loadbalancer.server.port=8080'
    networks:
      minikube:
        ipv4_address: '${IP_KEYCLOACK}'

  keycloak-postgres:
    image: 'postgres:14.15-alpine'
    container_name: 'keycloak-postgres'
    environment:
      POSTGRES_DB: 'keycloak'
      POSTGRES_USER: 'keycloak'
      POSTGRES_PASSWORD: 'changeme'
    volumes:
      - 'keycloak_postgres_data:/var/lib/postgresql/data'
    networks:
      minikube: {}

volumes:

  keycloak_postgres_data: {}
