---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nomadnamespaces.nomad.hashicorp.com
spec:
  group: nomad.hashicorp.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                provider:
                  type: string
                name:
                  type: string
                description:
                  type: string
                quota:
                  type: string
                meta:
                  type: object
                  additionalProperties:
                    type: string
                capabilities:
                  type: object
                  properties:
                    enabled_task_drivers:
                      type: array
                      items:
                        type: string
                    disabled_task_drivers:
                      type: array
                      items:
                        type: string
                node_pool_config:
                  type: object
                  properties:
                    default:
                      type: string
                    allowed:
                      type: array
                      items:
                        type: string
                    denied:
                      type: array
                      items:
                        type: string
              required:
                - provider
                - name
  scope: Namespaced
  names:
    plural: nomadnamespaces
    singular: nomadnamespace
    kind: NomadNamespace
    shortNames:
    - nn
