---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nomadnamespaces.nomad.hashicorp.com
spec:
  group: nomad.hashicorp.com
  scope: Namespaced
  names:
    plural: nomadnamespaces
    singular: nomadnamespace
    kind: NomadNamespace
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                provider:
                  type: string
                  description: "Specifies the provider to target."
                description:
                  type: string
                  description: "Specifies an optional human-readable description of the namespace."
                meta:
                  type: object
                  additionalProperties:
                    type: string
                  description: "Optional object with string keys and values of metadata to attach to the namespace."
                capabilities:
                  type: object
                  properties:
                    enabledTaskDrivers:
                      type: array
                      items:
                        type: string
                      description: "List of task drivers allowed in the namespace. If empty all task drivers are allowed."
                    disabledTaskDrivers:
                      type: array
                      items:
                        type: string
                      description: "List of task drivers disabled in the namespace."
                    enabledNetworkModes:
                      type: array
                      items:
                        type: string
                      description: "List of network modes allowed in the namespace. If empty all network modes are allowed."
                    disabledNetworkModes:
                      type: array
                      items:
                        type: string
                      description: "List of network modes disabled in the namespace."
                  description: "Specifies capabilities allowed in the namespace. These values are checked at job submission."
              required:
                - provider
          required:
            - spec
