---
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nomadproviders.nomad.hashicorp.com
spec:
  group: nomad.hashicorp.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                address:
                  type: string
                  default: "http://127.0.0.1:4646"
                region:
                  type: string
                http_auth:
                  type: string
                ca_file:
                  type: string
                ca_pem:
                  type: string
                cert_file:
                  type: string
                cert_pem:
                  type: string
                key_file:
                  type: string
                key_pem:
                  type: string
                skip_verify:
                  type: boolean
                  default: false
                headers:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                    required:
                      - name
                      - value
                vault_token:
                  type: string
                consul_token:
                  type: string
                secret_id:
                  type: string
                ignore_env_vars:
                  type: object
                  additionalProperties:
                    type: boolean
              required:
                - address
  scope: Namespaced
  names:
    plural: nomadproviders
    singular: nomadprovider
    kind: NomadProvider
    shortNames:
    - np
