apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nomadnamespaces.nomad.hashicorp.com
spec:
  group: nomad.hashicorp.com
  scope: Namespaced
  names:
    plural: nomadnamespaces
    singular: nomadnamespace
    kind: NomadNamespace
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
              - provider # The provider field is now required
            properties:
              provider:
                type: string
                description: "The name of the associated NomadProvider resource."
              description:
                type: string
                description: "A description of the namespace."
              quota:
                type: string
                description: "A resource quota to attach to the namespace."
              meta:
                type: object
                additionalProperties:
                  type: string
                description: "Specifies arbitrary key-value metadata to associate with the namespace."
              capabilities:
                type: object
                properties:
                  enabled_task_drivers:
                    type: array
                    items:
                      type: string
                    description: "Task drivers enabled for the namespace."
                  disabled_task_drivers:
                    type: array
                    items:
                      type: string
                    description: "Task drivers disabled for the namespace."
                description: "A block of capabilities for the namespace."
              node_pool_config:
                type: object
                properties:
                  default:
                    type: string
                    description: "The default node pool for jobs that don't define one."
                  allowed:
                    type: array
                    items:
                      type: string
                    description: "The list of node pools that are allowed to be used in this namespace."
                  denied:
                    type: array
                    items:
                      type: string
                    description: "The list of node pools that are not allowed to be used in this namespace."
                description: "A block with node pool configuration for the namespace (Nomad Enterprise only)."
    additionalPrinterColumns:
    - jsonPath: .spec.provider
      name: Provider
      type: string
    - jsonPath: .spec.description
      name: Description
      type: string
    - jsonPath: .spec.quota
      name: Quota
      type: string
