---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nomadnamespaces.nomad.hashicorp.com
spec:
  group: nomad.hashicorp.com
  scope: Namespaced
  names:
    plural: nomadnamespaces
    singular: nomadnamespace
    kind: NomadNamespace
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
    selectableFields:
    - jsonPath: .spec.name
    - jsonPath: .spec.description
    additionalPrinterColumns:
    - jsonPath: .spec.name
      name: Name
      type: string
    - jsonPath: .spec.description
      name: Description
      type: string
