apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - thanos-compact-service.yaml
  - thanos-compact-serviceAccount.yaml
  - thanos-compact-serviceMonitor.yaml
  - thanos-compact-statefulSet.yaml
  - thanos-query-deployment.yaml
  - thanos-query-service.yaml
  - thanos-query-serviceAccount.yaml
  - thanos-query-serviceMonitor.yaml
  - thanos-store-service.yaml
  - thanos-store-serviceAccount.yaml
  - thanos-store-serviceMonitor.yaml
  - thanos-store-statefulSet.yaml
