apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/

resources:
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/alertmanager-alertmanager.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/alertmanager-networkPolicy.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/alertmanager-podDisruptionBudget.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/alertmanager-prometheusRule.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/alertmanager-secret.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/alertmanager-service.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/alertmanager-serviceAccount.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/refs/tags/v0.14.0/manifests/alertmanager-serviceMonitor.yaml
