apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  thanos:
    image: quay.io/thanos/thanos:v0.37.2
    objectStorageConfig:
      key: thanos.yaml
      name: thanos-objstore-config
