---
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: nomad
spec:
  configuration: |
    terraform {
      backend "kubernetes" {
        secret_suffix     = "nomad"
        namespace         = "crossplane-system"
        in_cluster_config = true
      }
      required_providers {
        nomad = {
          source = "hashicorp/nomad"
          version = "2.4.0"
        }
      }
    }
    provider "nomad" {
      address = "http://192.168.49.21:4646"
      region = "europe"
      alias = "europe"
    }
