---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-resources
  namespace: argo-system
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  sources:
    - repoURL: https://github.com/gperreymond/k8s-nomad-operator.git
      targetRevision: main
      path: applications/crossplane-resources
      helm:
        releaseName: crossplane-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
