---
apiVersion: 'tf.upbound.io/v1beta1'
kind: 'Workspace'
metadata:
  name: 'kestra-flows'
spec:
  providerConfigRef:
    name: 'kestra'
  writeConnectionSecretToRef:
    name: outputs-kestra-flows
    namespace: terraform-system
  forProvider:
    source: Remote
    module: https://github.com/gperreymond/k8s-nomad-operator/terraform/modules/kestra
