---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  namespace: ${argo_cd_namespace}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: internal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://github.com/gperreymond/k8s-nomad-operator.git
      path: charts/remote-charts/alertmanager
      targetRevision: ${alertmanager.git_target_revision}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${alertmanager.destination}
