---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: ${argo_cd_namespace}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: internal
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://github.com/gperreymond/k8s-nomad-operator.git
      path: charts/remote-charts/prometheus-operator
      targetRevision: ${prometheus_operator.git_target_revision}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${prometheus_operator.destination}
